# Https 포트 설정
server:
  port: 8443
# 인증서 파일 경로 및 비밀번호 설정
  ssl:
    key-store: /Users/skyriv213/Desktop/paypick/be/keystore.p12
    key-store-type: PKCS12
    key-alias: myapp
    key-store-password: pigo0808

spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/ana?useSSL=false&allowPublicKeyRetrieval=true
