version : '3.8'

volumes:
  paypick-data: {}

services:

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ana
    ports:
      - 3306:3306
    volumes:
      - paypick-data:/var/lib/mysql

  backend:
    build:
      dockerfile: Dockerfile
    restart: always
    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/ana?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SERVER_PORT: 8443
      SERVER_SSL_KEY_STORE: /etc/ssl/localhost.p12
      SERVER_SSL_KEY_STORE_PASSWORD: 8759
      SERVER_SSL_KEY_STORE_TYPE: PKCS12
#      SERVER_SSL_KEY_ALIAS: myapp
    ports:
      - 8443:8443
    depends_on:
      - database



